# Generated by Django 3.0.4 on 2020-07-04 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Departamentos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habilidades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habilidades', models.CharField(max_length=50, verbose_name='Habilidades')),
            ],
            options={
                'verbose_name': 'Habilidad',
                'verbose_name_plural': 'Habilidades',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Nombres:')),
                ('last_name', models.CharField(max_length=50, verbose_name='Apellidos:')),
                ('job', models.CharField(choices=[('0', 'Administrador'), ('1', 'Gerente'), ('2', 'Contador'), ('3', 'Docente'), ('4', 'Director'), ('5', 'Almacenero'), ('6', 'Vigilante')], max_length=1, verbose_name='Trabajo:')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='empleados', verbose_name='Avatar')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Departamentos.Departamento')),
                ('habilidades', models.ManyToManyField(to='Empleados.Habilidades')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
            },
        ),
    ]
